source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Socket.IO-Client-Swift'
pod 'SwiftyJSON'
pod 'SlackTextViewController'
pod 'LoremIpsum', '~> 1.0'
pod 'SDWebImage'
